### PR TITLE
Typos in napi-macros.h

### PR DESCRIPTION
**Pull request by ralphtheninja**
Found some :bug:'s.

### CODE REVIEW

**Comment by mafintosh** [comment]
I was clearly a sleepy when i wrote that :)

**Comment by mafintosh** [comment]
1.4.1

**Comment by ralphtheninja** [comment]
> I was clearly a sleepy when i wrote that :)

Most likely a copy paste error :smile: 

Maybe we could write some tests for these macros? Could base it on the example.

**Comment by ralphtheninja** [comment]
cc @Jikstra

**Comment by mafintosh** [comment]
Yea tests would be great

**Pull request merged**
