### PR TITLE
Add NAPI_STATUS_THROWS() macro

### PR DESCRIPTION
**Pull request by ralphtheninja**
I originally named this macro `NAPI_CHECK_STATUS()` but it's doing similar things as `NAPI_UV_THROWS()` so I renamed it.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
I also have an improvement coming to `NAPI_ARGV()` which checks that the number of arguments you specified in c actually matches the number of arguments you give from js.

**Comment by ralphtheninja** [comment]
@mafintosh Is this too invasive? I could strip down internal usage if you like and just have the macro as is.

**Comment by mafintosh** [comment]
@ralphtheninja no this looks great! will merge when on my laptop

**Comment by ralphtheninja** [comment]
I still aim to write some tests in this module, but currently swamped with other stuff. We'll get there eventually!

**Comment by ralphtheninja** [comment]
@mafintosh Sorry to be a pain, but can we get this merged?

**Comment by mafintosh** [comment]
1.5.0

**Comment by mafintosh** [comment]
@ralphtheninja added you on npm and github also :)

**Pull request merged**
